In [1]:
import numpy as np
import tensorflow as tf
from numpy import array

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

# 1. 주어진 문장을 '단어'로 토큰화 하기

In [2]:
# 케라스의 텍스트 전처리와 관련한 함수중 text_to_word_sequence 함수를 불러 옵니다.
from tensorflow.keras.preprocessing.text import text_to_word_sequence

# 전처리할 텍스트를 정합니다.
text = '해보지 않으면 해낼 수 없다'

# 해당 텍스트를 토큰화 합니다.
result = text_to_word_sequence(text)
print("\n원문:\n", text)
print("\n토큰화:\n", result) 


원문:
 해보지 않으면 해낼 수 없다

토큰화:
 ['해보지', '않으면', '해낼', '수', '없다']


In [3]:
# 단어 빈도수 세기

# 세 개의 문장을 정의합니다.
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.',
       '텍스트의 단어로 토큰화 해야 딥러닝에서 토큰화 인식됩니다.',
       '토큰화 한 결과는 딥러닝에서 사용 할 수 있습니다.',
       ]

docs

['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.',
 '텍스트의 단어로 토큰화 해야 딥러닝에서 토큰화 인식됩니다.',
 '토큰화 한 결과는 딥러닝에서 사용 할 수 있습니다.']

In [4]:
# 토큰화 함수를 이용해 전처리 하는 과정
from tensorflow.keras.preprocessing.text import Tokenizer

token = Tokenizer()             # 토큰화 함수 지정
token.fit_on_texts(docs)        # 토큰화 함수에 문장 적용

token

In [5]:
# 각 단어 빈도수 : .word_counts
print("\n단어 카운트:\n", token.word_counts) 
# Tokenizer()의 word_counts 함수는 순서를 기억하는 OrderedDict클래스를 사용합니다.


단어 카운트:
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 4), ('합니다', 1), ('단어로', 1), ('해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('한', 1), ('결과는', 1), ('사용', 1), ('할', 1), ('수', 1), ('있습니다', 1)])


In [6]:
# 총 문장 수 : .document_count
print("\n문장 카운트: ", token.document_count)


문장 카운트:  3


In [7]:
# 각 단어가 몇개의 문장에 포함되어 있는가 : .word_docs
# 출력되는 순서는 랜덤
print("\n각 단어가 몇개의 문장에 포함되어 있는가:\n", token.word_docs)


각 단어가 몇개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'텍스트의': 2, '합니다': 1, '먼저': 1, '나누어': 1, '각': 1, '단어를': 1, '토큰화': 3, '인식됩니다': 1, '딥러닝에서': 2, '해야': 1, '단어로': 1, '수': 1, '사용': 1, '있습니다': 1, '한': 1, '결과는': 1, '할': 1})


In [8]:
# 각 단어에 매겨진 인덱스 값 : .word_index
print("\n각 단어에 매겨진 인덱스 값:\n",  token.word_index)


각 단어에 매겨진 인덱스 값:
 {'토큰화': 1, '텍스트의': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '나누어': 7, '합니다': 8, '단어로': 9, '해야': 10, '인식됩니다': 11, '한': 12, '결과는': 13, '사용': 14, '할': 15, '수': 16, '있습니다': 17}


# 2. 리뷰 감성분석 딥러닝 모델

In [9]:
# 텍스트 리뷰 10개를 정의합니다.
docs = ["너무 재밌네요","최고예요","참 잘 만든 영화예요","추천하고 싶은 영화입니다","한번 더 보고싶네요","글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","글쎄요 재미없어요"]

# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스를 지정합니다.
classes = array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [10]:
# 토큰화 
from tensorflow.keras.preprocessing.text import Tokenizer

token = Tokenizer()
token.fit_on_texts(docs)

token

In [11]:
# 단어 별 빈도 수 계산
token.word_counts

OrderedDict([('너무', 1),
             ('재밌네요', 1),
             ('최고예요', 1),
             ('참', 1),
             ('잘', 1),
             ('만든', 1),
             ('영화예요', 1),
             ('추천하고', 1),
             ('싶은', 1),
             ('영화입니다', 1),
             ('한번', 1),
             ('더', 1),
             ('보고싶네요', 1),
             ('글쎄요', 2),
             ('별로예요', 1),
             ('생각보다', 1),
             ('지루하네요', 1),
             ('연기가', 1),
             ('어색해요', 1),
             ('재미없어요', 1)])

In [12]:
# 각 단어에 매겨진 인덱스 값
print(len(token.word_index))
print(token.word_index)

20
{'글쎄요': 1, '너무': 2, '재밌네요': 3, '최고예요': 4, '참': 5, '잘': 6, '만든': 7, '영화예요': 8, '추천하고': 9, '싶은': 10, '영화입니다': 11, '한번': 12, '더': 13, '보고싶네요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [13]:
# 문장 별 토큰화 결과 확인
x = token.texts_to_sequences(docs)
print("\n리뷰 텍스트, 토큰화 결과:\n",  x)


리뷰 텍스트, 토큰화 결과:
 [[2, 3], [4], [5, 6, 7, 8], [9, 10, 11], [12, 13, 14], [1], [15], [16, 17], [18, 19], [1, 20]]


In [14]:
# 문장 최대 길이 확인
len_list = []
for i in range(len(x)):
    len_list.append(len(x[i]))

print("문장 별 길이:", len_list)
print("문장 최대 길이:", np.max(len_list))

문장 별 길이: [2, 1, 4, 3, 3, 1, 1, 2, 2, 2]
문장 최대 길이: 4


In [15]:
# 패딩, 서로 다른 길이의 데이터를 4로 맞추어 줍니다.
padded_x = pad_sequences(x, 4)    
print("\n패딩 결과:\n", padded_x)


패딩 결과:
 [[ 0  0  2  3]
 [ 0  0  0  4]
 [ 5  6  7  8]
 [ 0  9 10 11]
 [ 0 12 13 14]
 [ 0  0  0  1]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  1 20]]


### 테스트 데이터 만들기

In [16]:
test_docs = ["영화 재밌네요","올해 영화 중 최고예요","참 잘 만든 영화예요","추천하고 싶지 않은 영화입니다","두번 더 보고싶네요","글쎄요","아주 별로예요","생각보다 재미없네요","배우 연기가 어색해요","글쎄요 재미없어요"]

In [17]:
classes_test = array([1, 1, 1, 0, 1, 0, 0, 0, 0, 0])

In [39]:
# 토큰화 
from tensorflow.keras.preprocessing.text import Tokenizer
token_test = Tokenizer()
token_test.fit_on_texts(docs)
token_test

In [40]:
# 각 단어에 매겨진 인덱스 값
print(len(token_test.word_index))
print(token_test.word_index)

20
{'글쎄요': 1, '너무': 2, '재밌네요': 3, '최고예요': 4, '참': 5, '잘': 6, '만든': 7, '영화예요': 8, '추천하고': 9, '싶은': 10, '영화입니다': 11, '한번': 12, '더': 13, '보고싶네요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [41]:
# 문장 별 토큰화 결과 확인
test_x = token_test.texts_to_sequences(test_docs)
print("\n리뷰 텍스트, 토큰화 결과:\n",  test_x)


리뷰 텍스트, 토큰화 결과:
 [[3], [4], [5, 6, 7, 8], [9, 11], [13, 14], [1], [15], [16], [18, 19], [1, 20]]


In [42]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
test_padded_x = pad_sequences(test_x, 4) 
print("\n패딩 결과:\n", test_padded_x) 


패딩 결과:
 [[ 0  0  0  3]
 [ 0  0  0  4]
 [ 5  6  7  8]
 [ 0  0  9 11]
 [ 0  0 13 14]
 [ 0  0  0  1]
 [ 0  0  0 15]
 [ 0  0  0 16]
 [ 0  0 18 19]
 [ 0  0  1 20]]


### 딥러닝 모델

In [43]:
# 임베딩에 입력될 단어의 수를 지정합니다.(패딩 0까지 단어로 포함하기 위해 1을 더한다.)
word_size = len(token.word_index) + 1
word_size

21

In [44]:
# 단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과를 출력합니다.
model = Sequential()

# (임베딩 층) 입력 벡터 크기: 단어 인덱스 수(21), 출력 벡터 크기: 10(수정 가능), 텍스트 패딩 결과인 4개씩 단어 입력
model.add(Embedding(21, 10, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))  # 이진 분류(긍정/부정)

# 모델 컴파일
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [45]:
# 모델 학습 : 데이터로 패딩된 피처(padded_x)와 클래스를 넣어준다.
model.fit(padded_x, classes, epochs=20)

Epoch 1/20
1/1 [==============================] - 0s 464ms/step - loss: 0.7006 - accuracy: 0.3000
Epoch 2/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6985 - accuracy: 0.3000
Epoch 3/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6964 - accuracy: 0.4000
Epoch 4/20
1/1 [==============================] - 0s 9ms/step - loss: 0.6943 - accuracy: 0.4000
Epoch 5/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6922 - accuracy: 0.5000
Epoch 6/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6901 - accuracy: 0.6000
Epoch 7/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6881 - accuracy: 0.6000
Epoch 8/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6860 - accuracy: 0.6000
Epoch 9/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6839 - accuracy: 0.7000
Epoch 10/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6819 - accuracy: 0.7000
Epoch 11/20
1/1 [==================

In [46]:
model.metrics_names

['loss', 'accuracy']

In [54]:
model.evaluate(padded_x, classes)

1/1 [==============================] - 0s 36ms/step - loss: 0.6589 - accuracy: 0.8000


[0.6589407920837402, 0.800000011920929]

In [55]:
model.evaluate(test_padded_x, classes_test)

1/1 [==============================] - 0s 33ms/step - loss: 0.6644 - accuracy: 0.7000


[0.6643821001052856, 0.699999988079071]

In [56]:
model.predict(test_padded_x)

1/1 [==============================] - 0s 17ms/step


array([[0.48477888],
       [0.4990539 ],
       [0.5382853 ],
       [0.5010448 ],
       [0.5083648 ],
       [0.47449738],
       [0.46787125],
       [0.47892317],
       [0.4740861 ],
       [0.4856291 ]], dtype=float32)

In [53]:
classes_test

array([1, 1, 1, 0, 1, 0, 0, 0, 0, 0])

In [28]:
docs

['너무 재밌네요',
 '최고예요',
 '참 잘 만든 영화예요',
 '추천하고 싶은 영화입니다',
 '한번 더 보고싶네요',
 '글쎄요',
 '별로예요',
 '생각보다 지루하네요',
 '연기가 어색해요',
 '글쎄요 재미없어요']